# IP table 설정
# URL : https://metallb.universe.tf/configuration/
# kubectl apply -f 6_2_metallb_ip_config.yaml

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
